name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        channel: [stable, master]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.channel }}

      - run: flutter create sample

      - run: flutter widget-preview start
        working-directory: sample
